<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Send' => 'Отправить',
    'Home' => 'Главная',
    'Current tasks' => 'Текущие задачи',
    'Domain' => 'Домен',
    'Pages' => 'Страницы',
    'All pages' => 'Все страницы',
    'Date' => 'Дата',
    'Start' => 'Старт',
    'Stop' => 'Стоп',
    'Logout' => 'Выйти',
    'Enter domain' => 'Введите адрес сайта',
    'Download' => 'Скачать',
    'Image' => 'Изображение',
    'Scan again' => 'Проверить еще раз',
    'Delete' => 'Удалить',
    'Export' => 'Экспорт',
    'Empty title' => 'Пустой title',
    'Empty H1' => 'Пустой H1',
    'Empty alt' => 'Пустой alt',
    'Duplicate title' => 'Дубли title',
    'Duplicate h1' => 'Дубли h1',
    'Error' => 'Ошибка',
    'Please fill out the following fields to login' => 'Заполните следующие поля, чтобы войти',
    'Please fill out the following fields to sign up' => 'Заполните следующие поля, чтобы зарегистрироваться',
    'Name' => 'Имя',
    'Sign up' => 'Регистрация',
    'Login' => 'Вход',
    'Password' => 'Пароль',
    'Scanning site' => 'Сканируем сайт',
    'Scanning' => 'Скаринуется',
    'Url' => 'Ссылка',
    'HTTP code' => 'Код ответа',
    'Response time' => 'Время ответа',
    'Resource' => 'Источник',
    'Page' => 'Страница',
    'Page with images with empty alt' => 'Страница, где найдены изображения без alt',
    'Prev' => 'Пред',
    'Next' => 'След',
    'Pages to scan' => 'Страниц в задании',
    'Scanned pages' => 'Проверено страниц',
    'Spent time' => 'Затрачено времени',
    's' => 'с',
    'H1 quantity' => 'Кол-во H1',
    'Copy URL' => 'Копировать URL',
    'Chord generator' => 'Генератор аккордов',
    'Chord' => 'Аккорд',
    'Save' => 'Сохранить',
    'Copied' => 'Скопировано',
    'Meta-description' => 'Генератор аккордов для гитары. Полная база аккордов, аппаликатуры аккордов, аккорды в разных позициях. Изображения аккордов, ссылки на изображения аккордов. Guitar-chords.space',
    'Meta-description-list' => 'Полный список аккордов для гитары на сайте. Аппаликатуры аккордов, аккорды в разных позициях. Изображения аккордов, ссылки на изображения аккордов. Guitar-chords.space',
    'Guitar chord generator' => 'Генератор аккордов для гитары',
    'Show all' => 'Показать все',
    'Сomplete chord list' => 'Полный список аккордов',
    'Select all' => 'Выбрать все',
    'Select tone' => 'Выбрать ноту',
    'Menu' => 'Меню'
];
