<?php


namespace app\components;

use yii\web\Controller;
use Yii;

class FrontController extends Controller
{
    /**
     * Устанавливает язык сайта
     */
    public function init()
    {
        $app = Yii::$app;
        $url = explode('/', $app->request->url);
        $languages = array_keys($app->params['languages']);
        $app->language = $app->params['defaultLanguage'];
        if(isset($url[1]) && !empty($url[1]) && in_array($url[1], $languages)) {
            $app->language = $url[1];
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Редирект на страницу с вабранным языком
     *
     * @param \yii\base\Action $action
     * @return bool|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $app = Yii::$app;
        $language = Yii::$app->request->post('language');
        if($language) {
            $url = trim(Yii::$app->request->getLangUrl(), '/');
            $url = explode('/', $url);
            $langs = array_keys($app->params['languages']);
            if($language !== Yii::$app->params['defaultLanguage'] && in_array($language, $langs)) {
                array_unshift($url, $language);
            }
            return $this->redirect('/' . implode('/', $url), 301);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}