<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Send' => 'Send',
    'Home' => 'Home',
    'Current tasks' => 'Current tasks',
    'Domain' => 'Domain',
    'Pages' => 'Pages',
    'All pages' => 'All pages',
    'Date' => 'Date',
    'Start' => 'Start',
    'Stop' => 'Stop',
    'Logout' => 'Logout',
    'Enter domain' => 'Enter domain',
    'Download' => 'Download',
    'Scan again' => 'Scan again',
    'Delete' => 'Delete',
    'Export' => 'Export',
    'Empty title' => 'Empty title',
    'Empty H1' => 'Empty H1',
    'Empty alt' => 'Empty alt',
    'Duplicate title' => 'Duplicate title',
    'Duplicate h1' => 'Duplicate h1',
    'Error' => 'Error',
    'Please fill out the following fields to login' => 'Please fill out the following fields to login',
    'Please fill out the following fields to sign up' => 'Please fill out the following fields to sign up',
    'Name' => 'Name',
    'Sign up' => 'Sign up',
    'Login' => 'Login',
    'Password' => 'Password',
    'Scanning site' => 'Scanning site',
    'Meta-description' => 'Guitar chord generator. Complete variety of guitar chords, chords fingering, chords in different positions. Chords images, links to chords images.',
    'Meta-description-list' => 'Complete guitar chord list. Chords fingering, chords in different positions. Chords images, links to chords images. Guitar-chords.space',
];
